---
title: "GxE Effects..."
output: html_notebook
---

Could be worth exploring....


## What is the relative importance of plant genotype vs. food-web complexity in altering selection gradients?

Gall Size
```{r}
# RELATIONSHIP BETWEEN ABSOLUTE FITNESS AND GALL SIZE ACROSS GENOTYPES AND TREATMENTS
ggplot(gall_selection.df, aes(x=c.Gall_Height_mm, y=gall_survival, color=Treatment.focus)) +
  geom_point(shape=1) +
  geom_smooth(method = "lm", formula = y ~ x) +
  #geom_smooth(method = "lm", formula = y ~ poly(x,2), color="red") +
  facet_wrap(~Genotype, ncol=2)

ggplot(gall_selection.df, aes(x=c.Gall_Height_mm, y=gall_survival/mean(gall_survival))) +
  geom_point() + 
  geom_smooth(method="lm", formula=y~poly(x,2))

ggplot(gall_selection.df, aes(x=c.Gall_Height_mm, y=gall_survival, color=Treatment.focus)) +
  geom_point() + 
  geom_smooth(method="gam", formula=y~s(x), method.args = list(family=binomial(link="logit")))

ggplot(gall_selection.df, aes(x=c.Gall_Height_mm, y=gall_survival)) +
  geom_point() + 
  geom_smooth(method="gam", formula=y~s(x), method.args = list(family=binomial(link="logit"))) +
  facet_wrap(~Genotype)

ggplot(gall_selection.df, aes(x=c.Gall_Height_mm, y=gall_survival, color=Treatment.focus)) +
  geom_point() + 
  geom_smooth(method="lm", formula=y~poly(x,2)) +
  facet_wrap(~Genotype)


## ESTIMATE DIRECTIONAL SELECTION GRADIENTS ON GALL SIZE FOR EACH PLANT GENOTYPE AND FOOD-WEB TREATMENT
size.grad_models <- gall_selection.df %>%
  group_by(Treatment.focus, Genotype) %>%
  do(model = lm(gall_survival/mean(gall_survival) ~ I((Gall_Height_mm - mean(Gall_Height_mm))/sd(Gall_Height_mm)), data = .)) %>%
  tidy(model) %>%
  ungroup()
size.grad_models

## PLOT VARIATION IN SELECTION GRADIENTS FOR GALL SIZE AMONG PLANT GENOTYPES AND FOOD-WEB TREATMENTS
size.grad_models %>%
  filter(term != "(Intercept)") %>%
  ggplot(., aes(x=Genotype, y=estimate, fill=Treatment.focus)) +
  geom_errorbar(aes(ymax = estimate + std.error, ymin = estimate - std.error), #, color=Treatment.focus
                width = 0.5, position = position_dodge(width = 0.8)) +
  geom_point(shape=21, size = 2, position = position_dodge(width=0.8)) +
  geom_hline(yintercept = 0, linetype="dotted") 

## PLOT IN A REACTION NORM STYLE
size.grad_models %>%
  filter(term != "(Intercept)") %>%
  ggplot(., aes(x=Treatment.focus, y=estimate, fill=Genotype, group=Genotype)) +
  geom_line() +
  geom_point(shape=21, size=4) +
  geom_hline(yintercept=0, linetype="dotted")

mean_GxE <- gall_selection.df %>%
  group_by(Treatment.focus, Genotype) %>%
  summarise_at(vars(gall_survival, Gall_Height_mm), funs(mean))
mean_GxE


rel_fit_GxE <- c()
c.GxE.Gall_Height_mm <- c()
for(i in 1:dim(gall_selection.df)[1]){
  rel_fit_GxE[i] <- gall_selection.df$gall_survival[i]/filter(mean_GxE,
                                                          Treatment.focus==gall_selection.df$Treatment.focus[i],
                                                          Genotype==gall_selection.df$Genotype[i])$gall_survival
 # c.GxE.Gall_Height_mm <- gall_selection.df$Gall_Height_mm[i] - filter(mean_GxE,
#                                                          Treatment.focus==gall_selection.df$Treatment.focus[i],
#                                                          Genotype==gall_selection.df$Genotype[i])$Gall_Height_mm
}
gall_selection.df$rel_fit_GxE <- rel_fit_GxE
#gall_selection.df$c.GxE.Gall_Height_mm <- c.GxE.Gall_Height_mm

gall_selection.df$c.Gall_Height_mm <- gall_selection.df$Gall_Height_mm - mean(gall_selection.df$Gall_Height_mm)

library(sjstats)
rel_fit_GxE.lm <- lm(rel_fit_GxE ~ c.Gall_Height_mm + c.Gall_Height_mm:Genotype + c.Gall_Height_mm:Treatment.focus + c.Gall_Height_mm:Treatment.focus:Genotype, data = gall_selection.df, contrast = list(Genotype="contr.sum",Treatment.focus="contr.sum"))
summary(rel_fit_GxE.lm)
anova(rel_fit_GxE.lm)
anova_stats(rel_fit_GxE.lm)

## visual checks of regression model
visreg(rel_fit_GxE.lm) # confirms that relativizing fitness across genotypes and treatments worked
visreg(rel_fit_GxE.lm, xvar="c.Gall_Height_mm")
visreg(rel_fit_GxE.lm, xvar="c.Gall_Height_mm", by="Genotype")
visreg(rel_fit_GxE.lm, xvar="c.Gall_Height_mm", by="Treatment.focus")
```

```{r}
size_models <- gall_selection.df %>%
  group_by(Treatment.focus, Genotype) %>%
  do(model = lm(gall_survival ~ I(Gall_Height_mm-mean(Gall_Height_mm)), data = .)) %>%
  tidy(model) %>%
  ungroup()

size_models %>%
  ggplot(., aes(x=Genotype, y=estimate, fill=Treatment.focus)) +
  geom_errorbar(aes(ymax = estimate + std.error, ymin = estimate - std.error), #, color=Treatment.focus
                width = 0.5, position = position_dodge(width=0.8)) +
  geom_point(shape=21, size = 2, position = position_dodge(width=0.8)) +
  geom_hline(yintercept = 0, linetype="dotted") +
  facet_wrap(~term, scales = "free_y")

size_models %>%
  ggplot(., aes(x=Treatment.focus, y=estimate, fill=Genotype, group=Genotype)) +
  geom_line() +
  geom_point(shape=21, size=4) +
  geom_hline(yintercept=0, linetype="dotted") +
  facet_wrap(~term, scales = "free_y")
```

```{r}

size.geno <- gall_selection.df %>%
  group_by(Treatment.focus, Genotype) %>%
  summarise_at(vars(Gall_Height_mm), funs(mean))
size.geno
table(gall_selection.df$Genotype, gall_selection.df$Treatment.focus)

test <- size.grad_models %>%
  filter(term != "(Intercept)") %>%
  left_join(., size.geno) 

ggplot(test, aes(x=Gall_Height_mm, y=estimate, fill=Genotype, size=1/std.error)) +
  geom_point(shape=21) +
  facet_wrap(~Treatment.focus)

cor.test(test$estimate, test$Gall_Height_mm)
```

Number of individuals per gall

```{r}
gall_agg <- gall_selection.df %>%
  group_by(Genotype, Treatment.focus, Plant_Position, Gall_Number) %>%
  summarise_at(vars(gall_individuals, gall_survival), funs(mean)) %>%
  ungroup() %>%
  mutate(c.gall_individuals = gall_individuals - mean(gall_individuals))

ggplot(gall_agg, aes(x=c.gall_individuals, y=gall_survival/mean(gall_survival))) +
  geom_point() + 
  geom_smooth(method="lm", formula=y~poly(x,2))


ggplot(gall_agg, aes(x=c.gall_individuals, y=gall_survival, color=Treatment.focus)) +
  geom_smooth(method = "lm", formula = y ~ x) +
  #geom_smooth(method = "lm", formula = y ~ poly(x,2), color="red") +
  facet_wrap(~Genotype, ncol=2)

ggplot(gall_agg, aes(x=c.gall_individuals, y=gall_survival, color=Treatment.focus)) +
  geom_point() + 
  geom_smooth(method="gam", formula=y~s(x,k=9), method.args = list(family=binomial(link="logit")))


ind.grad_models <- gall_agg %>%
  group_by(Treatment.focus, Genotype) %>%
  do(model = lm(gall_survival/mean(gall_survival) ~ I(gall_individuals - mean(gall_individuals)), data = .)) %>%
  tidy(model) %>%
  ungroup()
ind.grad_models

ind.grad_models %>%
  filter(term != "(Intercept)") %>%
  ggplot(., aes(x=Genotype, y=estimate, fill=Treatment.focus)) +
  geom_errorbar(aes(ymax = estimate + std.error, ymin = estimate - std.error), #, color=Treatment.focus
                width = 0.5, position = position_dodge(width = 0.8)) +
  geom_point(shape=21, size = 2, position = position_dodge(width=0.8)) +
  geom_hline(yintercept = 0, linetype="dotted") 

## PLOT IN A REACTION NORM STYLE
ind.grad_models %>%
  filter(term != "(Intercept)") %>%
  ggplot(., aes(x=Treatment.focus, y=estimate, fill=Genotype, group=Genotype)) +
  geom_line() +
  geom_point(shape=21, size=4) +
  geom_hline(yintercept=0, linetype="dotted")

gall_mean_GxE <- gall_agg %>%
  group_by(Treatment.focus, Genotype) %>%
  summarise_at(vars(gall_survival, gall_individuals), funs(mean))
gall_mean_GxE

gall_rel_fit_GxE <- c()
for(i in 1:dim(gall_agg)[1]){
  gall_rel_fit_GxE[i] <- gall_agg$gall_survival[i]/filter(gall_mean_GxE,
                                                          Treatment.focus==gall_agg$Treatment.focus[i],
                                                          Genotype==gall_agg$Genotype[i])$gall_survival
}
gall_agg$rel_fit_GxE <- gall_rel_fit_GxE

gall_rel_fit_GxE.lm <- lm(rel_fit_GxE ~ c.gall_individuals + c.gall_individuals:Genotype + c.gall_individuals:Treatment.focus + c.gall_individuals:Treatment.focus:Genotype, data = gall_agg, contrast = list(Genotype="contr.sum",Treatment.focus="contr.sum"))
summary(gall_rel_fit_GxE.lm)
anova(gall_rel_fit_GxE.lm)
anova_stats(gall_rel_fit_GxE.lm)

## visual checks of regression model
visreg(gall_rel_fit_GxE.lm) # confirms that relativizing fitness across genotypes and treatments worked
visreg(gall_rel_fit_GxE.lm, xvar="c.gall_individuals")
visreg(gall_rel_fit_GxE.lm, xvar="c.gall_individuals", by="Genotype")
visreg(gall_rel_fit_GxE.lm, xvar="c.gall_individuals", by="Treatment.focus")
```

```{r}
ind_models <- gall_agg %>%
  group_by(Treatment.focus, Genotype) %>%
  do(model = lm(gall_survival ~ I(gall_individuals-mean(gall_individuals)), data = .)) %>%
  tidy(model) %>%
  ungroup()

ind_models %>%
  ggplot(., aes(x=Genotype, y=estimate, fill=Treatment.focus)) +
  geom_errorbar(aes(ymax = estimate + std.error, ymin = estimate - std.error), #, color=Treatment.focus
                width = 0.5, position = position_dodge(width=0.8)) +
  geom_point(shape=21, size = 2, position = position_dodge(width=0.8)) +
  geom_hline(yintercept = 0, linetype="dotted") +
  facet_wrap(~term, scales = "free_y")

ind_models %>%
  ggplot(., aes(x=Treatment.focus, y=estimate, fill=Genotype, group=Genotype)) +
  geom_line() +
  geom_point(shape=21, size=4) +
  geom_hline(yintercept=0, linetype="dotted") +
  facet_wrap(~term, scales = "free_y")
```

```{r}
ind.geno <- gall_agg %>%
  group_by(Treatment.focus, Genotype) %>%
  summarise_at(vars(gall_individuals), funs(mean))
ind.geno
table(gall_agg$Genotype, gall_agg$Treatment.focus)

test2 <- ind.grad_models %>%
  filter(term != "(Intercept)") %>%
  left_join(., ind.geno) 

ggplot(test2, aes(x=gall_individuals, y=estimate, fill=Genotype, size=1/std.error)) +
  geom_point(shape=21) +
  facet_wrap(~Treatment.focus)

cor.test(test2$estimate, test2$gall_individuals)
```

```{r}
plant_agg <- gall_selection.df %>%
  group_by(Genotype, Treatment.focus, Plant_Position) %>%
  summarise_at(vars(Density_per_100_shoots, gall_survival), funs(mean)) %>%
  ungroup() %>%
  mutate(c.Density_per_100_shoots = Density_per_100_shoots - mean(Density_per_100_shoots))

ggplot(plant_agg, aes(x=c.Density_per_100_shoots, y=gall_survival, color=Treatment.focus)) +
  geom_smooth(method = "lm", formula = y ~ x) +
  #geom_smooth(method = "lm", formula = y ~ poly(x,2), color="red") +
  facet_wrap(~Genotype, ncol=2)


ggplot(plant_agg, aes(x=c.Density_per_100_shoots, y=gall_survival/mean(gall_survival))) +
  geom_point() + 
  geom_smooth(method="gam", formula=y~s(x))
  #geom_smooth(method="lm", formula=y~poly(x,2))

ggplot(plant_agg, aes(x=c.Density_per_100_shoots, y=gall_survival, color=Treatment.focus)) +
  geom_point() + 
  geom_smooth(method="gam", formula=y~s(x), method.args = list(family=binomial(link="logit")))

density.grad_models <- plant_agg %>%
  group_by(Treatment.focus, Genotype) %>% #  
  do(model = lm(gall_survival/mean(gall_survival) ~ I((Density_per_100_shoots - mean(Density_per_100_shoots))/sd(Density_per_100_shoots)), data = .)) %>%
  tidy(model) %>%
  ungroup()
density.grad_models

density.grad_models %>%
  filter(term != "(Intercept)") %>%
  ggplot(., aes(x=Genotype, y=estimate, fill=Treatment.focus)) + # 
  geom_errorbar(aes(ymax = estimate + std.error, ymin = estimate - std.error), #, color=Treatment.focus
                width = 0.5, position = position_dodge(width = 0.8)) +
  geom_point(shape=21, size = 2, position = position_dodge(width=0.8)) +
  geom_hline(yintercept = 0, linetype="dotted") 

## PLOT IN A REACTION NORM STYLE
density.grad_models %>%
  filter(term != "(Intercept)") %>%
  ggplot(., aes(x=Treatment.focus, y=estimate, fill=Genotype, group=Genotype)) +
  geom_line() +
  geom_point(shape=21, size=4) +
  geom_hline(yintercept=0, linetype="dotted")

plant_mean_GxE <- plant_agg %>%
  group_by(Treatment.focus, Genotype) %>%
  summarise_at(vars(gall_survival, Density_per_100_shoots), funs(mean))
plant_mean_GxE

plant_rel_fit_GxE <- c()
for(i in 1:dim(plant_agg)[1]){
  plant_rel_fit_GxE[i] <- plant_agg$gall_survival[i]/filter(plant_mean_GxE,
                                                          Treatment.focus==plant_agg$Treatment.focus[i],
                                                          Genotype==plant_agg$Genotype[i])$gall_survival
}
plant_agg$rel_fit_GxE <- plant_rel_fit_GxE

plant_rel_fit_GxE.lm <- lm(rel_fit_GxE ~ c.Density_per_100_shoots + c.Density_per_100_shoots:Genotype + c.Density_per_100_shoots:Treatment.focus + c.Density_per_100_shoots:Treatment.focus:Genotype, data = plant_agg, contrast = list(Genotype="contr.sum",Treatment.focus="contr.sum"))
summary(plant_rel_fit_GxE.lm)
anova(plant_rel_fit_GxE.lm)
anova_stats(plant_rel_fit_GxE.lm)

## visual checks of regression model
visreg(plant_rel_fit_GxE.lm) # confirms that relativizing fitness across genotypes and treatments worked
visreg(plant_rel_fit_GxE.lm, xvar="c.Density_per_100_shoots")
visreg(plant_rel_fit_GxE.lm, xvar="c.Density_per_100_shoots", by="Genotype")
visreg(plant_rel_fit_GxE.lm, xvar="c.Density_per_100_shoots", by="Treatment.focus")
```

```{r}
density_models <- plant_agg %>%
  group_by(Treatment.focus, Genotype) %>%
  do(model = lm(gall_survival ~ I(Density_per_100_shoots-mean(Density_per_100_shoots)), data = .)) %>%
  tidy(model) %>%
  ungroup()

density_models %>%
  ggplot(., aes(x=Genotype, y=estimate, fill=Treatment.focus)) +
  geom_errorbar(aes(ymax = estimate + std.error, ymin = estimate - std.error), #, color=Treatment.focus
                width = 0.5, position = position_dodge(width=0.8)) +
  geom_point(shape=21, size = 2, position = position_dodge(width=0.8)) +
  geom_hline(yintercept = 0, linetype="dotted") +
  facet_wrap(~term, scales = "free_y")

density_models %>%
  ggplot(., aes(x=Treatment.focus, y=estimate, fill=Genotype, group=Genotype)) +
  geom_line() +
  geom_point(shape=21, size=4) +
  geom_hline(yintercept=0, linetype="dotted") +
  facet_wrap(~term, scales = "free_y")
```

```{r}
density.geno <- plant_agg %>%
  group_by(Treatment.focus, Genotype) %>%
  summarise_at(vars(Density_per_100_shoots), funs(mean))
density.geno
table(plant_agg$Genotype, plant_agg$Treatment.focus)

test3 <- density.grad_models %>%
  filter(term != "(Intercept)") %>%
  left_join(., density.geno) 

ggplot(test3, aes(x=Density_per_100_shoots, y=estimate, fill=Genotype, size=1/std.error)) +
  geom_point(shape=21) +
  facet_wrap(~Treatment.focus)

cor.test(test3$estimate, test3$Density_per_100_shoots)
```

### old but will likely use much of this




Analyze separate models for absolute fitness as a function of gall size for each treatment and genotype combination. 









```{r}
gall_selection.df$c.gall_individuals <- with(gall_selection.df, gall_individuals - mean(gall_individuals))

ind_GxE_lms <- lm(gall_survival ~ c.gall_individuals*Genotype*Treatment.focus, data = gall_selection.df, contrast = list(Genotype = "contr.sum"))
summary(ind_GxE_lms)
anova(ind_GxE_lms)
```

```{r}


agg.ind_GxE_lms <- lm(gall_survival ~ (c.gall_individuals + Genotype + Treatment.focus)^2, data = gall_agg, contrast = list(Genotype = "contr.sum"))
summary(agg.ind_GxE_lms)
anova(agg.ind_GxE_lms)
visreg(agg.ind_GxE_lms, xvar="c.gall_individuals", by="Treatment.focus")
visreg(agg.ind_GxE_lms, xvar="c.gall_individuals", by="Genotype")
```

```{r}
gall_selection.df$c.Density_per_100_shoots <- with(gall_selection.df, Density_per_100_shoots - mean(Density_per_100_shoots))

density_GxE_lms <- lm(gall_survival ~ (c.Density_per_100_shoots + Genotype + Treatment.focus)^2, data = gall_selection.df, contrast = list(Genotype = "contr.sum"))
summary(density_GxE_lms)
anova(density_GxE_lms)
```

```{r}
plant_agg <- gall_selection.df %>%
  group_by(Genotype, Treatment.focus, Plant_Position) %>%
  summarise_at(vars(Density_per_100_shoots, gall_survival), funs(mean)) %>%
  ungroup() %>%
  mutate(c.Density_per_100_shoots = Density_per_100_shoots - mean(Density_per_100_shoots))

agg.density_GxE_lms <- lm(gall_survival ~ c.Density_per_100_shoots*Genotype*Treatment.focus, data = plant_agg, contrast = list(Genotype = "contr.sum"))
summary(agg.density_GxE_lms)
anova(agg.density_GxE_lms)
```

```{r}
multivar_GxE_lms <- lm(gall_survival ~ Genotype*Treatment.focus*c.Gall_Height_mm, data = gall_selection.df, contrast = list(Genotype = "contr.sum", Treatment.focus="contr.sum"))
summary(multivar_GxE_lms)
car::vif(multivar_GxE_lms)
anova(multivar_GxE_lms)
visreg(multivar_GxE_lms, xvar="c.Gall_Height_mm", by="Treatment.focus")
visreg(multivar_GxE_lms, xvar="c.gall_individuals", by="Treatment.focus")
visreg(multivar_GxE_lms, xvar="c.Density_per_100_shoots", by="Treatment.focus")
visreg2d(multivar_GxE_lms, xvar="c.Density_per_100_shoots", yvar="c.gall_individuals")
```

```{r Piecewise SEM}
library(lme4)
library(lmerTest)
library(piecewiseSEM)

size_geno <- lm(Gall_Height_mm ~ Genotype, gall_selection.df, contrast = list(Genotype="contr.sum")) 
summary(size_geno)
sem.model.fits(size_geno)
anova(size_geno)

ind_geno <- lm(gall_individuals ~ Genotype, gall_selection.df, contrast = list(Genotype="contr.sum"))
summary(ind_geno)
sem.model.fits(ind_geno)
anova(ind_geno)

density_geno <- lmer(log(Density_per_100_shoots+1) ~ Genotype + (1|Plant_Position/Gall_Number/Gall_ID), gall_selection.df, contrast = list(Genotype="contr.sum"))
summary(density_geno)
sem.model.fits(density_geno)
anova(density_geno)

selection_grads <- lm(gall_survival ~ Treatment.focus*(Gall_Height_mm+gall_individuals+Density_per_100_shoots)^2, gall_selection.df)
sem.model.fits(selection_grads)

model.list <- list(size_geno, ind_geno, density_geno, selection_grads)

sem.fit(model.list, gall_selection.df, corr.errors = c("Gall_Height_mm~~gall_individuals","Gall_Height_mm~~Density_per_100_shoots","gall_individuals~~Density_per_100_shoots"))
```

```{r}
gall_selection.df %>%
  ggplot(., aes(x=c.Gall_Height_mm, y=gall_survival, color=Genotype)) +
  geom_smooth(method="lm") +
  facet_wrap(~Treatment.focus)

gall_agg %>%
  ggplot(., aes(x=c.gall_individuals, y=gall_survival, color=Genotype)) +
  geom_smooth(method="lm") +
  facet_wrap(~Treatment.focus)

plant_agg %>%
  ggplot(., aes(x=c.Density_per_100_shoots, y=gall_survival, color=Genotype)) +
  geom_smooth(method="lm") +
  facet_wrap(~Treatment.focus)
```

