---
title: "To_Do"
author: "Matt Barbour"
date: "8/1/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Updated

> Population all tables with R-code to make output reproducible

> Decide whether to include 3-way interaction and update models appropriately. Right now, I'm thinking I shouldn't, because it doesn't jive with estimating the gamma matrix and consequences for the curvature of the fitness landscape.

> Duplicate coefficient estimates for bootstrapped models.

> Put statistical analyses in the supplement to show that there was no differences in phenotypes among the food-web treatments.

> Consider a different way to subset the data: convert all estimates of "surviving" ectoparasitism to gall survival, even though this may include estimates of platygaster parasitism.

> Need a graph showing the conflicting selection pressure imposed on clutch size and oviposition preference in the complex food web.

> Consider calculate difference between curvature matrix of complex and simple food webs to describe the change in curvature

----

> look for uncompressed version of "complex_simple_foodwebs.pdf" on Ruthie or my Macbook

> Use standard regression model to determine significant differences in selection gradients.

> Log-transform predictor variables in order to get a best approximation of the fitness landscape. I can use AIC to justify or reject this idea.

> Add a 3-way trait interaction term to test for these higher-order effects.

> Standardize trait values at the level of the whole data set.

> Calculate selection differentials and estimate how much I may have overestimated the effects of selection on gall diameter.

> Test for differences in trait values among treatments to dispell this idea as a factor driving differences in my selection gradients.

> Change position of figure legend for univariate plots (try placing middle-top with 3 plots across.)

> Get bootstrapped estimates of selection intensity and compare between treatments/

> Fix axis labels on plots (change to mean fitness and trait values)

> Fix size of axis text on plots.

> Modify color of figures for illustration of simple and complex food webs and make uncompressed.

> Conduct an analysis that looks at the selection gradients imposed by each guild of parasitoids and visualizes it.

> Spend 10 min. trying to figure out how to double-space the manuscript.

> Tidy repo

> Draft Discussion

> Calculate selection gradients acting on Platygaster. This will enable me to have a discussion about potential indirect evolutionary cascades occuring via changes in network complexity.

