---
title: Food-web complexity flattens the fitness landscape of an insect herbivore
author:
  - name: Matthew A. Barbour
    email: matthew.barbour@ieu.uzh.ch
    affiliation: Department of Evolutionary Biology and Environmental Studies, University of Zurich, Zurich, Switzerland
    footnote: Corresponding Author
  - name: Jordi Bascompte
    email: jordi.bascompte@ieu.uzh.ch
    affiliation: Another University
address:
  - code: Some Institute of Technology
    address: Department, Street, City, State, Zip
  - code: Another University
    address: Department, Street, City, State, Zip
abstract: Studies of natural selection and fitness landscapes usually treat the network of interacting species as a “black box”. Given that the loss of biodiversity is simplifying the structure of ecological networks, there is a pressing need to answer the question: how does network complexity affect natural selection and the fitness landscape of associated species? To answer this question, we conducted a field experiment that manipulated the complexity of a food web associated with a galling insect herbivore. To maintain complex food webs, we allowed the entire community of natural enemies to attack insect galls on 64 plants in a common garden setting. To create simple food webs, we excluded a guild of three larval parasitoids by bagging galls on 64 different plants; therefore, mortality in this treatment was primarily due to a single egg parasitoid that attacks prior to gall formation. We then measured herbivore survival as a function of three key gall traits in each treatment. We found that more traits were under selection in the simple vs. complex food web. This occurred because different parasitoid species impose different selection pressures on gall traits, thereby minimizing relative fitness differences among insect galls with different phenotypes. Our work suggests that more complex food webs allow phenotypic variation to persist, which could facilitate subsequent adaptive evolution to environmental change.

Species-interaction networks provide a mechanistic link between community and population ecology, as they describe who interacts with whom in a community. Similarly, fitness landscapes provide a mechanistic link between population and evolutionary ecology, as they describe the influence of natural selection on phenotypic variation. It remains unclear, however, how the network structure of species interactions shapes the fitness landscape. Understanding this relationship is likely key for developing a predictive ecology across scales of biological organization. To examine the relationship between network structure and the fitness landscape, we conducted a field experiment that manipulated the network of trophic interactions (simple vs. complex) influencing the fitness of an insect herbivore. We then quantified the fitness landscape of herbivores in each treatment by measuring herbivore survival as a function of multiple phenotypic traits. We found that more traits were under selection in the simple vs. complex trophic network. This occurred because different natural enemies impose different selection pressures on herbivore traits, thereby minimizing relative fitness differences among herbivore phenotypes in the complex network. Our work suggests that more complex trophic networks allow phenotypic variation to persist, which could facilitate subsequent adaptive evolution of populations to environmental change.

bibliography: mybibfile.bib
output: rticles::elsevier_article
---

_Text based on elsarticle sample manuscript, see [http://www.elsevier.com/author-schemas/latex-instructions#elsarticle](http://www.elsevier.com/author-schemas/latex-instructions#elsarticle)_


Introduction
============

<!-- I. Community context can affect evolutionary change -->

Biological diversity -- from genes, to phenotypes, to species -- has fascinated evolutionary biologists for decades.

Much of this biological diversity has been shaped by natural selection via trophic interactions, such as resource competition (cite charater displacement), mutualistic exchanges of resource (cite? ), and predation (cite recent Heath and Stireman paper).

NEED to recognize that evolutionary biologists have begun to explore how community context affects evolutionary change (work by Sharon Strauss, Casey terHorst, Lutz Becks, etc.). These results have begun to show interesting patterns whereby the composition of species in a community can alter the direction and strength of natural selection imposed on species embedded within these communities (cite). 

Put another way, these results have begun to show biological diversity, in terms of differences between species, can drive evolutionary change. 

While there is clear evidence for pairwise trophic interactions to drive evolution by natural selection, its unclear how biological diversity itself imposes natural selection and drives evolutionary change.

<!-- II. Still unclear how biological diversity shapes evolutionary change -->

Exploring the effects of biological diversity requires an explicit examination of the network structure of trophic interactions between species in a community. Theoretical models have begun to examine how the network structure of species interactions drives evolutionary change (Nuismer paper; Guimeras paper; Ecology Letters paper from a spanish guy...); however, we are currently lacking experimental tests. 

<!-- II. Ecologists have incorporated community context --> 

In contrast, ecologists have begun to embrace the complexity of the natural world, and seeking to identify the complex networks of interactions that underlie community structure and ecosystem function. However, these studies have not examined how evolutionary processes feedback to shape the structure and evolution of these interaction networks.

<!-- III. Generate expectations for how food-web complexity may alter selection gradients -->

Food-web complexity may influence selection gradients in multiple ways. First, if more diverse predator communities are more efficient as suppressing prey densities (e.g. biodiversity-ecosystem fucntion; Ives 2005 Ecology Letters), then this will result in lower mean fitness. A reduction in mean fitness, all else equal, will intensify natural selection and thus could increase the rate of evolutionary change. Alternatively, if predators are functionally distinct, more diverse communities can reduce the strength of selection. This is because each predator has a different functional relationship between prey phenotype and the probability of an interaction. 

<!-- IV. Introduce study system -->

Here, we conducted a field experiment to test the effect of food-web complexity on the fitness landscape of a species embedded within this food web. To do this, we used a common garden experiment with a host plant (*Salix hooeriana*), an abundant herbivore (*Iteomyia salicisverruca*), and the diverse community of insect parasitoids that attack it. Prior work in this system has shown that there is directional selection for larger galls, likely because larger galls provide more of a refuge from parasitoid attack. However, there is also evidence that different parasitoid species impose differential selection on gall phenotypes.  

<!-- IV. Relationship between entropy and fitness landscape 
In more complex communities, there is greater uncertainty for an individual prey in which predator species will be imposing the trophic interaction. This also means the --> 



Materials & Methods
===================

<!-- I. Give details about the study site, but not focusing on the genetic variation since this doesn't play much of a role in this manuscript. -->

To isolate the effects of coastal willow (\textit{S. hookeriana} Barratt ex Hooker) genetic variation on the plant-insect food web, we used a common garden experiment consisting of 26 different willow genotypes (13 males; 13 females), located at Humboldt Bay National Wildlife Refuge (HBNWR) (40&deg;'53"N, 124&deg;12'4"W) near Loleta, California, USA. Willow genotypes were collected from a single population of willows growing around Humboldt Bay. While relatedness among these genotypes is unknown, their phenotypes in multivariate trait space are quite distinct from each other [@Barbour2016-hz], suggesting that we can treat them as independent from one another. This common garden was planted in February 2009 with 25 clonal replicates (i.e. stem cuttings) of each willow genotype in a completely randomized design in two hectares of a former cattle pasture at HBNWR. Willows in our garden begin flowering in February and reach their peak growth in early August. During this study, willows had reached 2 - 4 m in height. Further details on the genotyping and planting of the common garden are available in (@Barbour2015-tp).

We conducted our study within a common garden consisting of 26 different willow genotypes (13 males; 13 females), located at Humboldt Bay National Wildlife Refuge (HBNWR) (40&deg;40'53"N, 124&deg;12'4"W) near Loleta, California, USA. Willow genotypes were collected from a single population of willows growing around Humboldt Bay. While relatedness among these genotypes is unknown, their phenotypes in multivariate trait space are quite distinct from each other (Barbour et al. 2016), suggesting that we can treat them as independent from one another. This common garden was planted in February 2009 with 25 clonal replicates (i.e. stem cuttings) of each willow genotype in a completely randomized design in two hectares of a former cattle pasture at HBNWR. Willows in our garden begin flowering in February and reach their peak growth in early August. During this study, willows had reached 2 - 4 m in height. Further details on the genotyping and planting of the common garden are available in (Barbour et al. 2015). We conducted this experiment across 8 different plant genotypes that span the range of trait variation (Barbour et al. 2015).

<!-- II. Describe the food-web manipulation experiment --> 

We setup our food-web manipulation soon after galls began developing on \textit{S. hookeriana} in early June of 2013. On treatment plants, we enclosed 14 galled leaves with organza bags (MANUFACTORER DETAILS) to exclude three parasitoid species that attack during larva development (hereafter larval parasitoids). This treatment did not exclude the egg parasitoid \textit{Platygaster} sp. which attacks prior to gall initiation (note that in Cecidomyiid midges, larva initiate gall development CITE). On control plants, we used flagging tape to mark 14 galled leaves per plant, allowing the full suite of parasitoids to attack \textit{Iteomyia}. Marking galls with flagging tape ensured that we compared control and treatment galls with similar phenology when we collected galls later in the season. In late August 2013, we collected marked and bagged galls from each plant. We placed galls in 30 mL transport vials and allowed them to complete development for 4 months at room temperature in the lab. We opened galls under a dissecting scope and determined whether larva survived to pupation, our measure of fitness, or were parasitized. 

<!-- % III. Describe how we measured gall phenotypes -->

We collected data on three different phenotypes for each larva that have been shown to be important in our work (@Barbour2016) and in other work with Cecidomyiid midges (@Weis1983, @Heath2018). First, we measured the size of each gall chamber to the nearest 0.01 mm at its maximum diameter (perpendicular to the direction of plant tissue growth). Our previous work has shown that larger galls provide a refuge for larva from parasitoid attack (@Barbour2016). Second, we counted the number of chambers in each gall, which is indicative of the clutch size of adult female midges (@Weis1983). All larva collected from the same multi-chambered gall were scored with the same clutch size. Third, we estimated gall density as the number of larva per 100 shoots. We did this by summing the number of gall chambers for galls on five randomly sampled branches per tree. To account for potential differences in the number of shoots per branch for each plant genotype (CITE other willow work), we then counted the number of shoots on the fifth branch to estimate the number of larva per 100 shoots for each plant. All larva collected from the same plant were scored with the same gall density phenotype. This phenotype is indicative of the preference of female midges for particular plant traits (hereafter 'female preference'). 

The measurement of insect densities on a plant is a commonly used index for measuring oviposition preference (@Gripenberg2010), although it is controversal (@Singer1986)

<!-- % IV. Describe statistical analysis to test the effects of food-web complexity -->

We used generalized additive mixed models (GAMMs, cite Bolker et al. 2008) to test the effects of food-web complexity on the shape of fitness landscape. Larva survival (0 or 1) was our response variable and measure of fitness. We specified our food-web treatment, each gall trait, and all possible statistical interactions, as fixed effects to fully explore the effects of food-web complexity on the fitness landscape. This analysis implicitly assumes that selection is linear, which we felt was a necessary trade-off for exploring the shape of the fitness landscape. We specified plant genotype, plant individual nested within genotype, and multi-chambered gall nested within plant individual, as random effects.

To account for the correlated structure of our gall phenotypes (female preference at plant-level; clutch size at gall-level; chamber size at chamber-level), we specified gall ID nested within plant ID nested within plant genotype as random intercepts in our statistical models. 

From these GAMMs, we estimate selection gradients by assuming the mean value of our random effects (i.e. setting them to zero). This was appropriate for our analysis, since we were interested in estimating the fitness landscape, which is function of population mean fitness and mean trait values.

We used a spline-based semiparametric regression (Schluter 1988, Morrissey and Sakedra 2014). These analyses are desirable because they lead to inferences of the form of selection that make few \textit{a priori} assumptions (Schluter 1988), and can now be used to quantify standardized selection gradients (Morrissey and Sakrera 2014).

We then calculated selection gradients as the partial derivatives in absolute fitness (larva survival) with response to multivariate phenotype using the \textit{gsg} package in R (cite Morrissey and R project). We standardized phenotypes (mean=0, SD=1), so that first-order derivatives correspond to the intensity of directional selection ($\beta$\textsubscript{trait}), while second-order derivatives correspond to intensity of nonlinear ($\gamma$\textsubscript{trait}) and correlational selection ($\gamma$\textsubscript{trait$_i$,}\textsubscript{trait$_j$}) and are thus comparable within this study as well as to others.

Our GLMMs are useful for testing the effects of food-web complexity on the fitness landscape within the context of our experimental design; however, coefficients from GLMMs cannot be easily converted into quantitative estimates of selection gradients (cite Morrissey's work). Therefore, for each treatment, we fit separate generalized additive models (GAMs) for gall traits that we identified as being under selection from our GLMMs. Estimating selection gradients from GAMs can give insight to both linear and non-linear selection gradients, which we assumed were all linear for our GLMMs, given the complexity of already fitting up to 4-way interactions in these models. For the number of larva per gall and gall density, we aggregated larva survival at the gall or plant level, respectively, to avoid pseudoreplication in our GAMs. 

We used Aikaike Information Criteria to compare models that varied in complexity. This analysis enabled us to explore the appropriate complexity of the model to include for our analyses (i.e. include non-linear and correlational selection gradients and whether they varied with food-web treatment).

Results
=======

We found that more phenotypic traits were under selection in the simple vs. complex food web. In both complex and simple food webs, gall diameter was under strong directional selection, with larger galls resulting in higher larval survival (complex Beta = ; simple Beta = )(Fig. 2A). In complex food webs, there was no evidence of selection on clutch size ($\beta_{clutch}=$) or female preference ($\beta_{preference}=$)(orange lines in Fig. 2B,C). In simple food webs, however, clutch size and female preference were under strong directional selection, with smaller clutch sizes and weaker preferences resulting in higher larval survival (blue lines in Fig. 2B,C). These different selection pressures resulted in different adaptive landscapes in complex vs. simple food webs, with evidence for more rugged landscapes in the simple rather than the complex food web (Fig. 3). Depending on the trait combinations used to create the landscape, we found that the ruggedness of the adaptive landscape ranged from 10\% higher (Fig. 3A) to 274\% higher (Fig. 3C) in the simple vs. complex food web. Our model comparison suggested that it was unnecessary to test for the effects of non-linear or correlational selection gradients (ref. supp. mat.).

Discussion
==========


<!-- Feedbacks between biological diversity and evolutionary change -->

There are various bibliography styles available. You can select the
style of your choice in the preamble of this document. These styles are
Elsevier styles based on standard styles like Harvard and Vancouver.
Please use BibTeX to generate your bibliography and include DOIs
whenever available.

Here are two sample references: @Feynman1963118 [@Dirac1953888].

References {#references .unnumbered}
==========
